### ISSUE TITLE
Google Calendar api issue

### ISSUE THREAD

**Issue by AaronAce** [miguelarauj1o/CalendarQuickStart#6] opened 2017-02-16 05:21 UTC
![issues](https://cloud.githubusercontent.com/assets/23185026/23008468/cdd79110-f44a-11e6-8b43-a38b34e79670.png)

**Comment by miguelarauj1o** [comment] 2017-08-14 00:51
I'm closing this because I think this kind of question fits better in stackoverflow.
This project was intended to be a simple guide to start using the google calendar API.

**Closed as completed by miguelarauj1o** 2017-08-14 00:51 UTC
